name: Deploy mdBook to GitHub Pages

on:
  push:
    branches: ["main", "master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Cache Cargo dependencies and mdBook tools
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/mdbook
            ~/.cargo/bin/mdbook-epub
            ~/.cargo/bin/mdbook-pdf
            ~/.cargo/bin/mdbook-auto-gen-summary
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-mdbook-tools-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-mdbook-tools-

      - name: Install mdBook and plugins if not cached
        run: |
          [[ -f ~/.cargo/bin/mdbook ]] || cargo install mdbook --locked --no-default-features --features search
          [[ -f ~/.cargo/bin/mdbook-epub ]] || cargo install mdbook-epub --locked
          [[ -f ~/.cargo/bin/mdbook-pdf ]] || cargo install mdbook-pdf --locked
          [[ -f ~/.cargo/bin/mdbook-auto-gen-summary ]] || cargo install mdbook-auto-gen-summary --locked

      - name: Generate SUMMARY.md
        run: |
          rm -f src/SUMMARY.md
          mdbook-auto-gen-summary gen src

      - name: Build mdBook HTML
        run: mdbook build

      - name: Build mdBook EPUB
        run: mdbook-epub

      - name: Build mdBook PDF
        run: mdbook-pdf

      - name: Upload HTML artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: book/html

      - name: Upload EPUB artifact
        uses: actions/upload-artifact@v4
        with:
          name: book-epub
          path: book.epub

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: book-pdf
          path: book.pdf

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4